/*
 * Copyright (c) 2024, Gnosis Research Center, Illinois Institute of Technology
 * All rights reserved.
 *
 * This file is part of IOWarp Core.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 *
 * 3. Neither the name of the copyright holder nor the names of its
 *    contributors may be used to endorse or promote products derived from
 *    this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */

/**
 * GPU Work Orchestrator implementation
 *
 * A persistent GPU kernel that polls CPU->GPU and GPU->GPU queues for tasks,
 * dispatches them to GPU-side containers via gpu::Worker / gpu::PoolManager,
 * and communicates results back through FutureShm completion flags.
 *
 * Execution model: single-threaded polling with CUDA Dynamic Parallelism (CDP)
 * child kernel launches. Thread 0 polls queues and launches child kernels as needed.
 * Container tasks run in those child kernels rather than in the persistent kernel itself.
 *
 * All GPU containers are allocated within this CUDA module's context, so
 * virtual function dispatch (vtables) works correctly. No companion .so
 * files or function pointer fixups are needed.
 */

#if HSHM_ENABLE_CUDA || HSHM_ENABLE_ROCM

#include <time.h>
#include <unistd.h>

#include "chimaera/ipc_manager.h"
#include "chimaera/gpu/work_orchestrator.h"
#include "chimaera/gpu/container.h"
#include "chimaera/gpu/pool_manager.h"
#include "chimaera/gpu/worker.h"
#include "chimaera/config_manager.h"

// Include autogenerated GPU module registry (container headers + alloc kernel)
#include "autogen/gpu_work_orchestrator_modules.h"

namespace chi {

/**
 * GPU Work Orchestrator - persistent kernel for GPU task execution.
 * Thread 0 polls queues and launches GPU tasks via CUDA Dynamic Parallelism.
 * Runs with 1 block, 1 thread.
 */
__global__ void chimaera_gpu_orchestrator(gpu::PoolManager *pool_mgr,
                                           gpu::WorkOrchestratorControl *control,
                                           IpcManagerGpuInfo gpu_info,
                                           u32 num_blocks) {
  // Initialize IpcManager for this block
  // num_blocks is used to partition the backend memory among blocks.
  CHIMAERA_GPU_ORCHESTRATOR_INIT(gpu_info, num_blocks);

  __syncthreads();

  // Only thread 0 polls
  if (threadIdx.x == 0) {
    // Store gpu_info in device heap so CDP child kernels can access it
    // via pointer (IpcManagerGpuInfo can't be passed by value to kernels).
    IpcManagerGpuInfo *d_gpu_info = static_cast<IpcManagerGpuInfo *>(
        malloc(sizeof(IpcManagerGpuInfo)));
    if (d_gpu_info) {
      memcpy(d_gpu_info, &gpu_info, sizeof(IpcManagerGpuInfo));
    }

    gpu::Worker worker;
    worker.Init(0,           // worker_id
                gpu_info.cpu2gpu_queue,
                gpu_info.gpu2gpu_queue,
                gpu_info.internal_queue,
                pool_mgr,
                control->cpu2gpu_queue_base,
                control);
    worker.gpu_info_ptr_ = d_gpu_info;

    // Signal readiness after worker is fully initialized so the CPU
    // spin-wait in Launch()/Resume() only unblocks when polling is imminent.
    control->running_flag = 1;
    __threadfence_system();

    // Poll until exit signal — both GPU→GPU and CPU→GPU from same thread
    int loop_count = 0;
    printf("[ORCH] START gpu2gpu=%p internal=%p cpu2gpu=%p\n",
           (void*)worker.gpu2gpu_queue_,
           (void*)worker.internal_queue_,
           (void*)worker.cpu2gpu_queue_);
    while (worker.is_running_ && !control->exit_flag) {
      int g2g = worker.PollGpu2Gpu();
      worker.PollCpu2Gpu();
      if (g2g > 0) {
        printf("[ORCH] loop=%d g2g=%d\n", loop_count, g2g);
      }
      ++loop_count;
    }

    // Flush orchestrator profile to pinned host memory before shutdown
    worker.FlushProfile();
    worker.Finalize();
    if (d_gpu_info) free(d_gpu_info);
  }
}

//==============================================================================
// gpu::WorkOrchestrator out-of-class method implementations
//==============================================================================

/**
 * Launch the persistent GPU work orchestrator.
 * Runs with 1 block, 1 thread (CDP child kernels will handle actual task execution).
 */
bool gpu::WorkOrchestrator::Launch(const IpcManagerGpuInfo &gpu_info, u32 blocks,
                                    u32 threads_per_block,
                                    char *cpu2gpu_queue_base) {
  if (is_launched_) {
    return true;
  }

  // Allocate WorkOrchestratorControl in pinned host memory
  gpu::WorkOrchestratorControl *pinned_control = nullptr;
  cudaMallocHost(&pinned_control, sizeof(gpu::WorkOrchestratorControl));
  control_ = pinned_control;
  if (!control_) {
    HLOG(kError, "gpu::WorkOrchestrator: Failed to allocate control structure");
    return false;
  }
  memset(control_, 0, sizeof(gpu::WorkOrchestratorControl));
  control_->cpu2gpu_queue_base = cpu2gpu_queue_base;

  // Allocate gpu::PoolManager on device
  gpu::PoolManager *d_pm = hshm::GpuApi::Malloc<gpu::PoolManager>(
      sizeof(gpu::PoolManager));
  if (!d_pm) {
    HLOG(kError, "gpu::WorkOrchestrator: Failed to allocate GPU PoolManager");
    cudaFreeHost(control_);
    control_ = nullptr;
    return false;
  }
  d_pool_mgr_ = d_pm;

  // Initialize PoolManager on device (zero-initialize)
  gpu::PoolManager host_pm;
  hshm::GpuApi::Memcpy(d_pm, &host_pm, sizeof(gpu::PoolManager));

  // Set GPU limits for CDP
  cudaDeviceSetLimit(cudaLimitStackSize, 16384);
  cudaDeviceSetLimit(cudaLimitPrintfFifoSize, 4 * 1024 * 1024);
  cudaDeviceSetLimit(cudaLimitDevRuntimePendingLaunchCount, 4096);
  cudaDeviceSetLimit(cudaLimitDevRuntimeSyncDepth, 16);
  cudaDeviceSetLimit(cudaLimitMallocHeapSize, 32 * 1024 * 1024);

  // Create dedicated stream
  stream_ = hshm::GpuApi::CreateStream();

  // Save launch parameters (for Pause/Resume, though we run 1 block x 1 thread)
  blocks_ = blocks;
  threads_per_block_ = threads_per_block;

  // Prepare launch_info for single-threaded persistent kernel
  IpcManagerGpuInfo launch_info = gpu_info;

  // Set gpu2gpu queue depth to 8192 for CDP task launches
  // (This is typically configured elsewhere, but ensure it's large enough)
  launch_info.gpu2gpu_num_lanes = 1;
  launch_info.internal_num_lanes = 1;

  // Launch persistent GPU work orchestrator with 1 block, 1 thread
  HLOG(kInfo, "Launching GPU work orchestrator with 1 block, 1 thread (CDP-based)");
  chimaera_gpu_orchestrator<<<1, 1, 0,
      static_cast<cudaStream_t>(stream_)>>>(
      d_pm, control_, launch_info, 1);

  launched_num_warps_ = 1;
  is_launched_ = true;

  // Wait for the GPU kernel to signal it is actually running.
  // The first launch can take tens of seconds (CUDA context init, JIT warm-up).
  // Without this barrier, tasks submitted before running_flag==1 are queued
  // but never drained because the kernel has not started polling yet.
  HLOG(kInfo, "Waiting for GPU orchestrator kernel to start...");
  struct timespec t_start, t_now;
  clock_gettime(CLOCK_MONOTONIC, &t_start);
  while (!control_->running_flag) {
    usleep(50000);
    clock_gettime(CLOCK_MONOTONIC, &t_now);
    double elapsed = (t_now.tv_sec - t_start.tv_sec) +
                     (t_now.tv_nsec - t_start.tv_nsec) * 1e-9;
    if (elapsed > 60.0) {
      HLOG(kError, "GPU orchestrator failed to start within 60s");
      return false;
    }
  }
  clock_gettime(CLOCK_MONOTONIC, &t_now);
  HLOG(kInfo, "GPU orchestrator is running (started in %.1fs)",
       (float)((t_now.tv_sec - t_start.tv_sec) +
               (t_now.tv_nsec - t_start.tv_nsec) * 1e-9));
  return true;
}

/** Stop the GPU work orchestrator and free resources. */
void gpu::WorkOrchestrator::Finalize() {
  if (!is_launched_) {
    return;
  }

  if (control_) {
    control_->exit_flag = 1;
  }

  if (stream_) {
    hshm::GpuApi::Synchronize(stream_);
    hshm::GpuApi::DestroyStream(stream_);
    stream_ = nullptr;
  } else {
    hshm::GpuApi::Synchronize();
  }

  if (d_pool_mgr_) {
    hshm::GpuApi::Free(d_pool_mgr_);
    d_pool_mgr_ = nullptr;
  }
  if (control_) {
    cudaFreeHost(control_);
    control_ = nullptr;
  }

  is_launched_ = false;
  HLOG(kInfo, "GPU work orchestrator finalized");
}

/** Pause the GPU work orchestrator. */
void gpu::WorkOrchestrator::Pause() {
  if (!is_launched_) {
    return;
  }
  control_->exit_flag = 1;
  HLOG(kInfo, "GPU work orchestrator: exit_flag set, waiting for kernel...");

  cudaError_t pre_err = cudaGetLastError();
  if (pre_err != cudaSuccess) {
    HLOG(kError, "GPU work orchestrator: pre-sync CUDA error: {}",
         cudaGetErrorString(pre_err));
  }

  hshm::GpuApi::Synchronize(stream_);
  HLOG(kInfo, "GPU work orchestrator: kernel synchronized");
  is_launched_ = false;
}

/**
 * Pre-allocate resources for the next Resume (if needed).
 * No cross-warp resources in CDP model; this is mostly a no-op.
 */
void gpu::WorkOrchestrator::PrepareResume() {
  // No special preparation needed for CDP single-thread model
  // The orchestrator always runs as 1 block x 1 thread
}

/** Resume a paused GPU work orchestrator. */
void gpu::WorkOrchestrator::Resume(const IpcManagerGpuInfo &gpu_info) {
  if (is_launched_) {
    return;
  }

  cudaError_t pre_err = cudaGetLastError();
  if (pre_err != cudaSuccess) {
    HLOG(kError, "GPU work orchestrator Resume: clearing sticky CUDA error: {}",
         cudaGetErrorString(pre_err));
  }

  control_->exit_flag = 0;
  control_->running_flag = 0;
  // Do NOT bump scratch_gen or reinit scratch — GPU container metadata
  // (e.g. CTE GpuMetadata with targets, tags, blobs) must persist
  // across pause/resume cycles.

  IpcManagerGpuInfo resume_info = gpu_info;
  resume_info.gpu2gpu_num_lanes = 1;
  resume_info.internal_num_lanes = 1;

  auto *d_pm = static_cast<gpu::PoolManager *>(d_pool_mgr_);

  // Resume with 1 block, 1 thread (CDP model)
  chimaera_gpu_orchestrator<<<1, 1, 0,
      static_cast<cudaStream_t>(stream_)>>>(
      d_pm, control_, resume_info, 1);

  cudaError_t launch_err = cudaGetLastError();
  if (launch_err != cudaSuccess) {
    HLOG(kError, "GPU work orchestrator Resume: kernel launch failed: {}",
         cudaGetErrorString(launch_err));
    is_launched_ = false;
    return;
  }

  is_launched_ = true;
  HLOG(kInfo, "GPU work orchestrator resumed (1 block, 1 thread CDP model)");
}

/**
 * Register a GPU container with the device-side PoolManager.
 */
void gpu::WorkOrchestrator::RegisterGpuContainer(const PoolId &pool_id,
                                                   void *gpu_container_ptr) {
  if (!d_pool_mgr_ || !gpu_container_ptr) {
    return;
  }

  auto *d_pm = static_cast<gpu::PoolManager *>(d_pool_mgr_);
  gpu::PoolManager host_pm;
  hshm::GpuApi::Memcpy(&host_pm, d_pm, sizeof(gpu::PoolManager));
  host_pm.RegisterContainer(pool_id,
                             static_cast<gpu::Container *>(gpu_container_ptr));
  hshm::GpuApi::Memcpy(d_pm, &host_pm, sizeof(gpu::PoolManager));

  HLOG(kInfo, "Registered GPU container for pool {}", pool_id);
}

/**
 * Allocate a GPU container by module name.
 * Uses the autogenerated allocation kernel which runs in this CUDA module's
 * context, ensuring vtables are correct.
 */
void *gpu::WorkOrchestrator::AllocGpuContainer(const PoolId &pool_id,
                                                 u32 container_id,
                                                 const std::string &chimod_name) {
  return gpu::AllocGpuContainerHost(pool_id, container_id, chimod_name.c_str());
}

//==============================================================================
// gpu_init_queue_kernel — device kernel for ArenaAllocator + GpuTaskQueue init
//==============================================================================

__global__ void gpu_init_queue_kernel(char *device_data, size_t capacity,
                                       u32 num_lanes, u32 queue_depth,
                                       size_t *d_out_off) {
  if (blockIdx.x != 0 || threadIdx.x != 0) return;

  hipc::MemoryBackend proxy;
  proxy.data_ = device_data;
  proxy.data_capacity_ = capacity;

  CHI_QUEUE_ALLOC_T *alloc = proxy.MakeAlloc<CHI_QUEUE_ALLOC_T>();
  if (!alloc) { *d_out_off = static_cast<size_t>(-1); return; }

  hipc::FullPtr<GpuTaskQueue> q = alloc->template NewObj<GpuTaskQueue>(
      alloc, num_lanes, 2, queue_depth);
  *d_out_off = q.IsNull() ? static_cast<size_t>(-1) : q.shm_.off_.load();
}

hipc::FullPtr<GpuTaskQueue> gpu::InitQueueOnDevice(char *device_data,
                                                  size_t capacity,
                                                  u32 num_lanes,
                                                  u32 queue_depth) {
  size_t *d_out_off = nullptr;
  cudaError_t err = cudaMalloc(&d_out_off, sizeof(size_t));
  if (err != cudaSuccess) {
    HLOG(kError, "InitQueueOnDevice: cudaMalloc for d_out_off failed: {}",
         cudaGetErrorString(err));
    return hipc::FullPtr<GpuTaskQueue>::GetNull();
  }

  // Use a dedicated stream to avoid blocking on persistent kernels
  // that may be running on other streams (e.g., client kernels).
  // cudaDeviceSynchronize() and default-stream cudaMemcpy would deadlock
  // if a persistent kernel is active on another stream.
  cudaStream_t init_stream;
  cudaStreamCreate(&init_stream);
  gpu_init_queue_kernel<<<1, 1, 0, init_stream>>>(device_data, capacity,
                                                    num_lanes, queue_depth,
                                                    d_out_off);
  err = cudaStreamSynchronize(init_stream);
  if (err != cudaSuccess) {
    HLOG(kError, "InitQueueOnDevice: kernel launch failed: {}",
         cudaGetErrorString(err));
    cudaStreamDestroy(init_stream);
    cudaFree(d_out_off);
    return hipc::FullPtr<GpuTaskQueue>::GetNull();
  }

  size_t off = static_cast<size_t>(-1);
  cudaMemcpyAsync(&off, d_out_off, sizeof(size_t), cudaMemcpyDeviceToHost,
                  init_stream);
  cudaStreamSynchronize(init_stream);
  cudaStreamDestroy(init_stream);
  cudaFree(d_out_off);

  hipc::FullPtr<GpuTaskQueue> result;
  if (off == static_cast<size_t>(-1)) {
    return hipc::FullPtr<GpuTaskQueue>::GetNull();
  }
  result.shm_.off_ = off;
  result.shm_.alloc_id_ = hipc::AllocatorId(0, 0);
  result.ptr_ = reinterpret_cast<GpuTaskQueue *>(device_data + off);
  return result;
}

}  // namespace chi

#endif  // HSHM_ENABLE_CUDA || HSHM_ENABLE_ROCM
